# Partially based on my config for Z490 10600K platform with iGPU enabled
# WARNING! THIS IS JUST AN EXAMPLE! DO NOT USE WITHOUT PREVIOUS EDIT

use: 0.6.9-RELEASE
arch: X64

acpi:
  copy:  # Copy from assets
    - SSDT-AWAC.aml
    - SSDT-EC-USBX-DESKTOP.aml
    - SSDT-PLUG-DRTNIA.aml
  quirks:  # Direct merge
    ResetLogoStatus: true

booter:
  quirks:  # Direct merge
    DevirtualiseMmio: true
    EnableWriteUnprotector: false
    ProtectUefiServices: true
    RebuildAppleMemoryMap: true
    SetupVirtualMap: false
    SyncRuntimePermissions: true


iGPU:  # Alias for PciRoot(0x0)/Pci(0x2,0x0) and enables specify special syntax
  platformId: "07009B3E"  # Alias for AAPL,ig-platform-id
  deviceId: "9B3E0000"

  connectors:  # Patches for connectors
    con3:
      # Automatically adds framebuffer-con3-enable
      flags: "20000000"
      index: "FFFFFFFF"
      pipe: "00000000"
      type: "00080000"  # In future will be able to specify just by typing HDMI or DP
  binaryProperties:
    framebuffer-stolenmem: "00003001"


kernel:
  kexts:
    copy:
      - Lilu
      - VirtualSMC
      - SMCProcessor
      - AirportItlwm
      - LucyRTL8125Ethernet
      - AppleAlc
      - WhateverGreen
      - RestrictEvents
    get:
      - Lilu:1.5.3
      - AppleAlc:1.6.0
      - WhateverGreen:1.4.9
      - RestrictEvents:1.0.1

  quirks:  # Direct merge
    AppleXcpmCfgLock: true
    DisableIOMapper: true
    LapicKernelPanic: false
    PanicNoKextDump: true
    PowerTimeoutKernelPanic: true
    XhciPortLimit: true

misc:
  boot:
    PickerMode: External
  debug:  # Direct merge
    Target: 3
  security:  # Direct merge
    AllowNvramReset: true
    AllowSetDefault: true
    BlacklistAppleUpdate: true
    ScanPolicy: 0
    SecureBootModel: Default
    Vault: Optional

nvram:
  bootArgs: alcid=1 agdpmod=pikera
  lang: "pl-PL:30788"

platform:
  type: iMac20,1
  serial: C02XG0FDH7JY
  boardSerial: C02839303QXH69FJA
  smUUID: DBB364D6-44B2-4A02-B922-AB4396F16DA8

uefi:
  drivers:
    - HfsPlus.efi
    - OpenRuntime.efi
    - OpenCanopy.efi
  tools:
    - OpenShell.efi

directCopy:
  # Everything in this section is just merged into Sample.plist (WARNING! eVeRyThInG hErE is CASE sensitive)
  UEFI:
    Quirks:
      UnblockFsConnect: true
