import Composition from './interfaces/composition'
import { PlistObject } from 'plist'
import mergeDeep from 'merge-deep'
import { AcpiAdd } from './interfaces/acpiAdd'

export default class Composer {
  readonly composition: Composition

  constructor (composition: Composition) {
    this.composition = composition
  }

  private generateAcpiAdd () {
    return {
      ACPI: {
        Add: this.composition.acpi?.copy?.map((name) => {
          const addEntry: AcpiAdd = {
            Comment: 'Added by composer',
            Enabled: true,
            Path: name
          }
          return addEntry
        }) ?? []
      }
    }
  }

  private generatePlatformUpdates () {
    return {
      PlatformInfo: {
        Generic: {
          MLB: this.composition.platform.boardSerial,
          SystemProductName: this.composition.platform.type,
          SystemSerialNumber: this.composition.platform.serial,
          SystemUUID: this.composition.platform.smUUID
        }
      }
    }
  }

  // cleaning config and target
  private static removeWarnings (config: Record<string, any>): PlistObject {
    delete config['#WARNING - 1']; delete config['#WARNING - 2']; delete config['#WARNING - 3']; delete config['#WARNING - 4']
    return config
  }

  private static cleanConfigBeforeMerge (config: Record<string, any>): PlistObject {
    config = this.removeWarnings(config)
    config['#Copyright'] = 'Generated by OC Composer'

    config.ACPI.Add = []
    config.Kernel.Add = []
    return config
  }

  mergeWith (config: PlistObject): PlistObject {
    config = Composer.cleanConfigBeforeMerge(config)

    return mergeDeep(
      config,
      this.generateAcpiAdd(),
      this.generatePlatformUpdates()
    ) as PlistObject
  }
}
